### web
server:
  port: 8095
  servlet:
    context-path: /nbatch

### actuator
management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false

### resources
spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  ### freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
      new_builtin_class_resolver: safer
  ### datasource-pool
  ### xxl-job, datasource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${NBATCH_ADMIN_DATASOURCE_URL:jdbc:mysql://localhost:3306/batch_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true}
    username: ${NBATCH_ADMIN_DATASOURCE_USERNAME:root}
    password: ${NBATCH_ADMIN_DATASOURCE_PASSWORD:}
    driver-class-name: ${NBATCH_ADMIN_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    hikari:
      # 连接池名称
      pool-name: HikariCP
      # 最小空闲连接数，保持10个连接以应对突发请求
      minimum-idle: 10
      # 最大连接池大小，同时最多30个数据库连接
      maximum-pool-size: 30
      # 自动提交从池中返回的连接
      auto-commit: true
      # 空闲连接超时时间（毫秒），30秒后关闭多余的空闲连接
      idle-timeout: 30000
      # 连接最大生命周期（毫秒），15分钟后强制关闭连接
      max-lifetime: 900000
      # 连接超时时间（毫秒），等待连接的最大时间为10秒
      connection-timeout: 10000
      # 连接测试查询，用于验证连接的有效性
      connection-test-query: SELECT 1
      # 连接验证超时时间（毫秒），1秒内完成连接有效性检查
      validation-timeout: 5000
  mail:
    host: ${NBATCH_MAIL_HOST:smtp.qq.com}
    port: ${NBATCH_MAIL_PORT:25}
    username: ${NBATCH_MAIL_USERNAME:}
    from: ${NBATCH_MAIL_FROM:${NBATCH_MAIL_USERNAME:}}
    password: ${NBATCH_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
# application.yml
logging:
  config: classpath:logback-spring.xml
  level:
    org.apache.ibatis: DEBUG
    com.dmap: DEBUG

### mybatis
mybatis-plus:
  mapper-locations: classpath:/sqlmap/**/*Mapper.xml
  # 搜索指定包别名
  type-aliases-package: com.nbatch.**.domain.po
  configuration:
    #开启日志打印
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #关闭日志打印
    #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    #是否开启 MyBatis 二级缓存。
    cache-enabled: false
    #允许JDBC 支持自动生成主键
    use-generated-keys: true
    #是否开启驼峰命名转换
    map-underscore-to-camel-case: true

xxl:
  job:
    accessToken: ${NBATCH_ACCESS_TOKEN:default_token}
    timeout: ${NBATCH_ADMIN_TIMEOUT:3}
    i18n: ${NBATCH_ADMIN_I18N:zh_CN}
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: ${NBATCH_ADMIN_LOG_RETENTION_DAYS:30}
