# web port
server:
  port: 8097

# log config
logging:
  config: classpath:logback-spring.xml
  level:
    org.apache.ibatis: DEBUG
    com.dmap: DEBUG
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    dynamic:
      # 配置默认数据库,及没有注解指定时走的数据库
      primary: gauss
      #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      lazy:  true
      datasource:
        gauss:
          url: ${NBATCH_GAUSS_DATASOURCE_URL:jdbc:opengauss://localhost:5432/postgres?currentSchema=public&serverTimezone=Asia/Shanghai}
          username: ${NBATCH_GAUSS_DATASOURCE_USERNAME:}
          password: ${NBATCH_GAUSS_DATASOURCE_PASSWORD:}
          driver-class-name: ${NBATCH_GAUSS_DATASOURCE_DRIVER:org.opengauss.Driver}
          hikari:
            min-idle: 1
            max-pool-size: 1
            is-auto-commit: true
            idle-timeout: 30000
            max-lifetime: 900000
            connection-timeout: 10000
            connection-test-query: SELECT 1
            validation-timeout: 1000
        clickhouse:
          url: ${NBATCH_CLICKHOUSE_DATASOURCE_URL:jdbc:clickhouse://localhost:8123/default?compress=0}
          username: ${NBATCH_CLICKHOUSE_DATASOURCE_USERNAME:default}
          password: ${NBATCH_CLICKHOUSE_DATASOURCE_PASSWORD:}
          driver-class-name: ${NBATCH_CLICKHOUSE_DATASOURCE_DRIVER:com.clickhouse.jdbc.ClickHouseDriver}
          hikari:
            min-idle: 1
            max-pool-size: 1
            is-auto-commit: true
            idle-timeout: 30000
            max-lifetime: 900000
            connection-timeout: 10000
            connection-test-query: SELECT 1
            validation-timeout: 1000
        gbase:
          url: ${NBATCH_GBASE_DATASOURCE_URL:jdbc:gbase://localhost:5258/default}
          username: ${NBATCH_GBASE_DATASOURCE_USERNAME:}
          password: ${NBATCH_GBASE_DATASOURCE_PASSWORD:}
          driver-class-name: ${NBATCH_GBASE_DATASOURCE_DRIVER:com.gbase.jdbc.Driver}
          hikari:
            min-idle: 1
            max-pool-size: 1
            is-auto-commit: true
            idle-timeout: 30000
            max-lifetime: 900000
            connection-timeout: 10000
            connection-test-query: SELECT 1
            validation-timeout: 1000
  jackson:
    time-zone: GMT+8
# xxl-job configuration
nbatch:
  job:
    admin:
      addresses: ${NBATCH_ADMIN_ADDRESSES:http://localhost:8095/nbatch}
      accessToken: ${NBATCH_ACCESS_TOKEN:default_token}
      timeout: ${NBATCH_CONSUMER_ADMIN_TIMEOUT:3}
    executor:
      appName: ${NBATCH_EXECUTOR_APP_NAME:nbatch-consumer}
      address: ${NBATCH_EXECUTOR_ADDRESS:}
      ip: ${NBATCH_EXECUTOR_IP:}
      port: ${NBATCH_EXECUTOR_PORT:9999}
      logpath: ${NBATCH_EXECUTOR_LOG_PATH:/log/nbatch/jobhandler}
      datapath: ${NBATCH_EXECUTOR_DATA_PATH:/data/nbatch/jobhandler}
      logretentiondays: ${NBATCH_EXECUTOR_LOG_RETENTION_DAYS:30}
    file:
      tempPath: ${NBATCH_FILE_TEMP_PATH:./file/temp}
      remoteTempPath: ${NBATCH_FILE_REMOTE_TEMP_PATH:./file/temp}

